<h1>NUMPY</h1>
Array processing package.Has bindings of c++ libraries

<h2>Array</h2>
An array is like a lsit. The only diferrence is that an array has only one data type inside it

In [1]:
import numpy as np

In [3]:
#create a list
my_lst=[1,2,3,4,5]
type(my_lst)

list

In [4]:
#convert it to an array
arr=np.array(my_lst)
type(arr)

numpy.ndarray

In [6]:
# the .shape() functions returns the dimensions
arr.shape

(5,)

<h3>2-D arrays</h3>

In [11]:
#create some lists
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[9,8,7,8,9]

#create the 2-d array
arr=np.array([lst1,lst2,lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 8, 9]])

In [12]:
#check shape
arr.shape

(3, 5)

<h4>Reshaping</h4>

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 8, 9]])

In [14]:
#we can also reshape it to be a row, but it will still remain a 2-d array
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 8, 7, 8, 9]])

<h3>Indexing</h3>

In [15]:
#accessing the elements of an array
arr1=np.array([1,2,3,4,5,56])

#retrieving an item
arr1[0]

1

In [16]:
#will give back all rows and columns
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 8, 9]])

In [17]:
# arr[column,row]
# arr[from which column:to which, from which row:to each]
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [18]:
arr[1,1:4]

array([3, 4, 5])

In [24]:
#np.arrage()   parameters(start,stop,step)
arr2=np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

In [27]:
#linspace(start,stop,step)
arr3=np.linspace(0,10,50)   #will create an array of 50 numbers between o and 10
arr3

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

<h2>Copying</h2>

In [29]:
#create an array
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr1[3:]=100 #this will turn all items from 3rd to 100
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [33]:
arr5=np.array([1,2,3,500,500,500,500,500,500])
arr5

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [37]:
#the .copy() functions willl create a copy instead of referencing
arr5=arr1.copy()
arr5

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [41]:
#now if we change sth in arr1, arr 5 will not be affected
arr1[4:]=0
print(arr1)
print(arr5)

[  1   2   3 100   0   0   0   0   0]
[  1   2   3 100 100 100 100 100 100]


<h3>Some interesting conditions</h3>

In [44]:
#let's define a value
val=5
print(arr5)
arr5<val

[  1   2   3 100 100 100 100 100 100]


array([ True,  True,  True, False, False, False, False, False, False])

In [43]:
arr5*val
# and we can do all other types of opretaions sa /,% etc

array([  5,  10,  15, 500, 500, 500, 500, 500, 500])

In [45]:
#we can also use this to return certain items
arr5[arr5<5]

array([1, 2, 3])

<h3>Some functions</h3>

In [48]:
#np.ones(number, data_type)
np.ones(4)    #we can omit the second paramenter of data type

array([1., 1., 1., 1.])

In [47]:
np.ones(4,int)

array([1, 1, 1, 1])

In [49]:
#create 2-d array
np.ones([2,3],int)

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
#random distribution
np.random.rand(3)

array([0.02911529, 0.3047824 , 0.73385022])

In [53]:
np.random.rand(3,2)

array([[0.31839412, 0.2108725 ],
       [0.28760347, 0.50675676],
       [0.07619652, 0.67385282]])

In [56]:
np.random.randn(4)     #standard normal distribution

array([ 1.42249486, -0.41232223,  0.55552403,  0.29497196])

In [62]:
# if paramenters are (x,y,z) we get z ints with values between x and y
np.random.randint(0,100,8)   #from 0 to 100 select 8 numbers

array([87, 55, 51, 74, 74, 58, 63, 71])

In [63]:
#between 0 and 1
np.random.random_sample(2)

array([0.56413357, 0.5908863 ])

In [64]:
#we can also get a 2-d array
np.random.random_sample((2,5))

array([[0.44615817, 0.06765537, 0.45433711, 0.68113673, 0.41448852],
       [0.96190287, 0.19625398, 0.67698914, 0.75607719, 0.6290569 ]])